Task 3.
ankarut/movies_tasks pull request #3
Opened 2016-09-22 05:35 UTC by ankarut

2016-09-23 07:23 UTC, zverok commented on movies.rb
> +}
это, кстати, излишне (важно замечать, когда решение можно упростить): строки с датами а форме yyyy-mm-dd и так отсортируются в разумном порядке ;)

2016-09-23 07:26 UTC, zverok commented on movies.rb
> +puts directors.sort_by { |n| n[:lname] }.map { |n| n[:fname] + ' ' + n[:lname] }
а короче всё это (строки 41-47)? в одно выражение-цепочку вызовов? типа просто map{ режиссёр}.sort_by{фамилия режиссёра}? 

мы в руби очень любим такие цепочки, они читабельнее!

2016-09-23 07:28 UTC, zverok commented on movies.rb
> +end
его ж можно использовать выводя результаты предыдущих задачкаэ (иначе этот метод низачем)

2016-09-23 07:32 UTC, zverok requested changes
По логике всё логично, но одна из важных вещей для рубиста - стремиться к определённому стилю кода - компактному и читабельному. В частности, по возможности оформлять одну логическую операцию в одно выражение, и минимизировать дополнительные временные переменные - как правило, у Руби хватает для этого фич ;)

2016-09-23 17:20 UTC, ankarut commented
Внесла изменения :)

2016-09-24 07:15 UTC, zverok approved these changes
:+1:

2016-09-24 12:35 UTC, merged